# Generated by Django 3.2.12 on 2022-02-20 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icd_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2)),
                ('emergency_phone_number', models.CharField(max_length=15)),
                ('expired_time', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='district_admin.facility')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='district_admin.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientVisitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_center.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientVisitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('palliative_phase', models.CharField(max_length=12)),
                ('blood_pressure', models.CharField(max_length=10)),
                ('pulse', models.IntegerField()),
                ('general_random_blood_sugar', models.CharField(max_length=10)),
                ('personal_hygiene', models.TextField()),
                ('mouth_hygiene', models.TextField()),
                ('public_hygiene', models.TextField()),
                ('systemic_examination', models.CharField(choices=[('cardiovascular', 'Cardiovascular'), ('gastrointestinal', 'Gastrointestinal'), ('respiratory', 'Respiratory'), ('genitourinary', 'Genital-urinary')], max_length=20)),
                ('patient_at_pease', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(choices=[('fever', 'Fever'), ('cough', 'Cough'), ('sore_throat', 'Sore throat')], max_length=23)),
                ('notes', models.TextField()),
                ('patient_visit_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_center.patientvisitschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('landmark', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(choices=[('brother', 'Brother'), ('sister', 'Sister'), ('husband', 'Husband'), ('wife', 'Wife'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('nephew', 'Nephew'), ('niece', 'Niece'), ('cousin', 'Cousin'), ('other', 'Other')], max_length=20)),
                ('education_level', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_center.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_center.disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_center.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
