# Generated by Django 3.2.12 on 2022-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0002_alter_patientvisitdetail_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfamilymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
