# Generated by Django 3.2.12 on 2022-02-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0003_patientfamilymember_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfamilymember',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
