# Generated by Django 3.2.12 on 2022-02-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0005_patientfamilymember_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitdetail',
            name='palliative_phase',
            field=models.CharField(choices=[('stable', 'Stable'), ('unstable', 'Unstable'), ('deteriotive', 'Deteriotive'), ('dying', 'Dying')], max_length=12),
        ),
        migrations.AlterField(
            model_name='patientvisitdetail',
            name='systemic_examination',
            field=models.CharField(choices=[('cardiovascular', 'Cardiovascular'), ('gastrointestinal', 'Gastrointestinal'), ('cns', 'Central Nervous System'), ('respiratory', 'Respiratory'), ('genitourinary', 'Genital-urinary')], max_length=20),
        ),
    ]
