# Generated by Django 3.2.12 on 2022-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0009_patienttreatment_treatmentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisitschedule',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
