# Generated by Django 3.2.12 on 2022-02-26 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_center', '0010_patientvisitschedule_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='given_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
