# Generated by Django 3.2.12 on 2022-02-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0011_patienttreatment_given_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatment',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='health_center.patientdisease'),
        ),
    ]
