# Generated by Django 3.2.12 on 2022-02-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0013_remove_patientvisitdetail_pain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisitschedule',
            name='time',
        ),
    ]
