# Generated by Django 3.2.12 on 2022-02-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_center', '0014_remove_patientvisitschedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisitdetail',
            name='mouth_hygiene',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisitdetail',
            name='personal_hygiene',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisitdetail',
            name='public_hygiene',
            field=models.TextField(blank=True, null=True),
        ),
    ]
