# Generated by Django 3.2.12 on 2022-02-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='localbody',
            options={'verbose_name_plural': 'Local Bodies'},
        ),
    ]
