# Generated by Django 3.2.12 on 2022-02-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district_admin', '0003_facility_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
