# Generated by Django 3.2.12 on 2022-02-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_admin', '0004_alter_facility_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='phc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chc', to='district_admin.facility'),
        ),
    ]
