# Generated by Django 3.2.12 on 2022-02-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('district_admin', '0005_facility_phc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='phc',
        ),
        migrations.AddField(
            model_name='facility',
            name='chc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phc_set', to='district_admin.facility'),
        ),
    ]
